language: python
python:
  - "3.5"
sudo: required
branches:
  only:
  - master
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - make publish
deploy:
  provider: pages
  repo: gustavofoa/dicasdejava.com.br
  target_branch: gp-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
